version: 2
updates:
  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      app-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /cli
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      cli-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      docs-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /shared
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      shared-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 10
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      github-actions-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - patch
      github-actions-minor:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
      github-actions-major:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - major
