name: Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  quality:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      run-dependency-review: false
    secrets: inherit

  # TODO: Figure out deployment model, and decide if we're going to do the deploy on each push to main (probably).  It may or may not be GH pages though.
  # deploy-pages:
  #   runs-on: ubuntu-latest
  #   needs: quality
  #   permissions:
  #     contents: read
  #     pages: write
  #     id-token: write
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     # actions/checkout@v5.0.0
  #     - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
  #     # actions/setup-node@v6.2.0
  #     - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
  #       with:
  #         node-version: 24
  #         cache: npm
  #         cache-dependency-path: |
  #           app/package-lock.json
  #           docs/package-lock.json
  #     - run: npm ci
  #       working-directory: app
  #     - run: npm ci
  #       working-directory: docs
  #     - run: SLIDE_SPEC_DEPLOYMENT_URL=https://slide-spec.dev/slides SLIDE_SPEC_SITEMAP_ENABLED=true npm run typecheck && npx vite build --base /slides/ && node --import tsx scripts/generate-site-files.ts
  #       working-directory: app
  #     - run: npm run build
  #       working-directory: docs
  #     - run: mkdir -p .pages/slides && cp -R docs/.vitepress/dist/. .pages/ && cp -R app/dist/. .pages/slides/
  #     # actions/configure-pages@v5.0.0
  #     - uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b
  #     # actions/upload-pages-artifact@v4.0.0
  #     - uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
  #       with:
  #         path: .pages
  #     - id: deployment
  #       # actions/deploy-pages@v4.0.5
  #       uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e

  slides-artifact:
    runs-on: ubuntu-latest
    needs: quality
    steps:
      # actions/checkout@v5.0.0
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd
      # actions/setup-node@v6.2.0
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: app/package-lock.json
      - run: npm ci
        working-directory: app
      - run: SLIDE_SPEC_DEPLOYMENT_URL=https://slide-spec.dev/slides SLIDE_SPEC_SITEMAP_ENABLED=true npm run typecheck && npx vite build --base /slides/ && node --import tsx scripts/generate-site-files.ts
        working-directory: app
      # actions/upload-artifact@v7.0.0
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          name: slides-dist
          path: app/dist
