name: PR

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  quality:
    uses: ./.github/workflows/reusable-quality.yml
    with:
      run-dependency-review: true
    secrets: inherit
